# -*- coding: utf-8 -*-
"""3rd_decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12b3yYlO60fQgTN5PLWh0aZmR5hXOzO8p

importing libraries
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

"""load the datatset"""

iris_data = pd.read_csv('iris.csv')

"""check the number of unique species"""

iris_data.Species.nunique()

"""Define features and target variable"""

features = iris_data.drop('Species', axis=1)  # Features
target = iris_data['Species']  # Target variable

"""split data into training and testing sets"""

features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=42)

"""Create Decision Tree classifier and train it"""

classifier = DecisionTreeClassifier()
classifier.fit(features_train, target_train)

"""predictions on the test set"""

target_pred = classifier.predict(features_test)
model_accuracy = accuracy_score(target_test, target_pred)
confusion_mat = confusion_matrix(target_test, target_pred)

"""print the results"""

print("Accuracy:", model_accuracy)
print("Confusion Matrix:\n", confusion_mat)